[package]
name = "weather"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
